# fly.toml app configuration file generated for car-management-api on 2024-07-08T13:54:09+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'car-management-api'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  ENVIRONMENT = 'production'
  SECRET_TOKEN = '09f26e402586e2faa8da4c98a35f1b20d6b033c6097befa8be3486a829587fe2f90a832bd3ff9d42710a4da095a2ce285b009f0c3730cd9b8e1af3eb84df6611'
  CLOUD_NAME = 'ddpbwjjfz'
  API_KEY = '978931698348746'
  API_SECRET = '6aJUsabfVgJns-wvPluvObUCRTE'  PRODUCTION_HOST = 'ep-bold-leaf-a27i2rk7.eu-central-1.pg.koyeb.app'
  PRODUCTION_USERNAME = 'koyeb-adm'
  PRODUCTION_PASSWORD = 'EeCGz9uO7nTl'
  PRODUCTION_DATABASE = 'binar_car_rental'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1